/******************************************************************************
 * Spleen 5x8 -> LVGL v9 1-bpp font (printable ASCII 0x20-0x7E +
 * the U+2500 box-drawing glyphs Spleen ships).
 * Generated by scripts/gen-spleen-font.py from Spleen's BDF; do not edit.
 *
 * Spleen (c) 2018-2026 Frederic Cambus, BSD-2-Clause.
 * https://github.com/fcambus/spleen
 ******************************************************************************/

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
    #include "lvgl.h"
#else
    #include "lvgl.h"
#endif

#ifndef LV_FONT_SPLEEN_5X8
    #define LV_FONT_SPLEEN_5X8 1
#endif

#if LV_FONT_SPLEEN_5X8

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    /* U+0020 ' ' */
    0x00, 0x00, 0x00, 0x00, 0x00,
    /* U+0021 '!' */
    0x21, 0x08, 0x42, 0x00, 0x80,
    /* U+0022 '"' */
    0x52, 0x94, 0x00, 0x00, 0x00,
    /* U+0023 '#' */
    0x02, 0xbe, 0xa5, 0x7d, 0x40,
    /* U+0024 '$' */
    0x23, 0xa8, 0xc3, 0x1b, 0x84,
    /* U+0025 '%' */
    0x14, 0xa8, 0x44, 0x2a, 0x50,
    /* U+0026 '&' */
    0x22, 0x94, 0xca, 0xc9, 0xa0,
    /* U+0027 ''' */
    0x21, 0x08, 0x00, 0x00, 0x00,
    /* U+0028 '(' */
    0x11, 0x10, 0x84, 0x20, 0x82,
    /* U+0029 ')' */
    0x41, 0x04, 0x21, 0x08, 0x88,
    /* U+002A '*' */
    0x00, 0x24, 0xcf, 0x32, 0x40,
    /* U+002B '+' */
    0x00, 0x08, 0x4f, 0x90, 0x80,
    /* U+002C ',' */
    0x00, 0x00, 0x00, 0x10, 0x88,
    /* U+002D '-' */
    0x00, 0x00, 0x0f, 0x00, 0x00,
    /* U+002E '.' */
    0x00, 0x00, 0x00, 0x00, 0x80,
    /* U+002F '/' */
    0x10, 0x88, 0x44, 0x22, 0x10,
    /* U+0030 '0' */
    0x03, 0x25, 0x6d, 0x49, 0x80,
    /* U+0031 '1' */
    0x01, 0x18, 0x42, 0x11, 0xc0,
    /* U+0032 '2' */
    0x03, 0x24, 0x26, 0x43, 0xc0,
    /* U+0033 '3' */
    0x03, 0x24, 0x41, 0x49, 0x80,
    /* U+0034 '4' */
    0x04, 0x29, 0x4f, 0x10, 0x80,
    /* U+0035 '5' */
    0x07, 0xa1, 0xc1, 0x0b, 0x80,
    /* U+0036 '6' */
    0x03, 0x21, 0xc9, 0x49, 0x80,
    /* U+0037 '7' */
    0x07, 0xa4, 0x22, 0x21, 0x00,
    /* U+0038 '8' */
    0x03, 0x24, 0xc9, 0x49, 0x80,
    /* U+0039 '9' */
    0x03, 0x25, 0x27, 0x09, 0x80,
    /* U+003A ':' */
    0x00, 0x00, 0x40, 0x00, 0x80,
    /* U+003B ';' */
    0x00, 0x00, 0x40, 0x10, 0x88,
    /* U+003C '<' */
    0x00, 0x88, 0x84, 0x10, 0x40,
    /* U+003D '=' */
    0x00, 0x01, 0xe0, 0x78, 0x00,
    /* U+003E '>' */
    0x02, 0x08, 0x21, 0x11, 0x00,
    /* U+003F '?' */
    0x64, 0x84, 0x44, 0x01, 0x00,
    /* U+0040 '@' */
    0x03, 0x25, 0x6b, 0x41, 0xc0,
    /* U+0041 'A' */
    0x03, 0x25, 0x2f, 0x4a, 0x40,
    /* U+0042 'B' */
    0x07, 0x25, 0xc9, 0x4b, 0x80,
    /* U+0043 'C' */
    0x03, 0xa1, 0x08, 0x41, 0xc0,
    /* U+0044 'D' */
    0x07, 0x25, 0x29, 0x4b, 0x80,
    /* U+0045 'E' */
    0x03, 0xa1, 0xc8, 0x41, 0xc0,
    /* U+0046 'F' */
    0x03, 0xa1, 0x0e, 0x42, 0x00,
    /* U+0047 'G' */
    0x03, 0xa1, 0x69, 0x49, 0xc0,
    /* U+0048 'H' */
    0x04, 0xa5, 0xe9, 0x4a, 0x40,
    /* U+0049 'I' */
    0x03, 0x88, 0x42, 0x11, 0xc0,
    /* U+004A 'J' */
    0x03, 0x88, 0x42, 0x13, 0x00,
    /* U+004B 'K' */
    0x04, 0xa5, 0xc9, 0x4a, 0x40,
    /* U+004C 'L' */
    0x04, 0x21, 0x08, 0x41, 0xc0,
    /* U+004D 'M' */
    0x04, 0xbd, 0xe9, 0x4a, 0x40,
    /* U+004E 'N' */
    0x04, 0xb5, 0xab, 0x5a, 0x40,
    /* U+004F 'O' */
    0x03, 0x25, 0x29, 0x49, 0x80,
    /* U+0050 'P' */
    0x07, 0x25, 0x2e, 0x42, 0x00,
    /* U+0051 'Q' */
    0x03, 0x25, 0x29, 0x49, 0x86,
    /* U+0052 'R' */
    0x07, 0x25, 0x2e, 0x4a, 0x40,
    /* U+0053 'S' */
    0x03, 0xa0, 0xc1, 0x0b, 0x80,
    /* U+0054 'T' */
    0x07, 0xc8, 0x42, 0x10, 0x80,
    /* U+0055 'U' */
    0x04, 0xa5, 0x29, 0x49, 0xc0,
    /* U+0056 'V' */
    0x04, 0xa5, 0x29, 0x31, 0x80,
    /* U+0057 'W' */
    0x04, 0xa5, 0x2f, 0x7a, 0x40,
    /* U+0058 'X' */
    0x04, 0xa4, 0xc6, 0x4a, 0x40,
    /* U+0059 'Y' */
    0x04, 0xa5, 0x27, 0x0b, 0x80,
    /* U+005A 'Z' */
    0x07, 0x84, 0x44, 0x43, 0xc0,
    /* U+005B '[' */
    0x72, 0x10, 0x84, 0x21, 0x0e,
    /* U+005C '\\' */
    0x84, 0x10, 0x82, 0x10, 0x42,
    /* U+005D ']' */
    0x70, 0x84, 0x21, 0x08, 0x4e,
    /* U+005E '^' */
    0x01, 0x15, 0x10, 0x00, 0x00,
    /* U+005F '_' */
    0x00, 0x00, 0x00, 0x00, 0x1e,
    /* U+0060 '`' */
    0x41, 0x00, 0x00, 0x00, 0x00,
    /* U+0061 'a' */
    0x00, 0x18, 0x27, 0x49, 0xc0,
    /* U+0062 'b' */
    0x84, 0x39, 0x29, 0x4b, 0x80,
    /* U+0063 'c' */
    0x00, 0x1d, 0x08, 0x41, 0xc0,
    /* U+0064 'd' */
    0x10, 0x9d, 0x29, 0x49, 0xc0,
    /* U+0065 'e' */
    0x00, 0x1d, 0x2f, 0x41, 0xc0,
    /* U+0066 'f' */
    0x32, 0x11, 0xc4, 0x21, 0x00,
    /* U+0067 'g' */
    0x00, 0x1d, 0x29, 0x30, 0x5c,
    /* U+0068 'h' */
    0x84, 0x39, 0x29, 0x4a, 0x40,
    /* U+0069 'i' */
    0x01, 0x00, 0xc2, 0x10, 0xc0,
    /* U+006A 'j' */
    0x01, 0x00, 0x42, 0x10, 0x98,
    /* U+006B 'k' */
    0x84, 0x25, 0x4c, 0x52, 0x40,
    /* U+006C 'l' */
    0x42, 0x10, 0x84, 0x20, 0xc0,
    /* U+006D 'm' */
    0x00, 0x25, 0xef, 0x4a, 0x40,
    /* U+006E 'n' */
    0x00, 0x39, 0x29, 0x4a, 0x40,
    /* U+006F 'o' */
    0x00, 0x19, 0x29, 0x49, 0x80,
    /* U+0070 'p' */
    0x00, 0x39, 0x29, 0x72, 0x10,
    /* U+0071 'q' */
    0x00, 0x1d, 0x29, 0x38, 0x42,
    /* U+0072 'r' */
    0x00, 0x1d, 0x28, 0x42, 0x00,
    /* U+0073 's' */
    0x00, 0x1d, 0x06, 0x0b, 0x80,
    /* U+0074 't' */
    0x42, 0x38, 0x84, 0x20, 0xc0,
    /* U+0075 'u' */
    0x00, 0x25, 0x29, 0x49, 0xc0,
    /* U+0076 'v' */
    0x00, 0x25, 0x29, 0x31, 0x80,
    /* U+0077 'w' */
    0x00, 0x25, 0x2f, 0x7a, 0x40,
    /* U+0078 'x' */
    0x00, 0x24, 0xc6, 0x4a, 0x40,
    /* U+0079 'y' */
    0x00, 0x25, 0x29, 0x38, 0x5c,
    /* U+007A 'z' */
    0x00, 0x3c, 0x22, 0x23, 0xc0,
    /* U+007B '{' */
    0x32, 0x11, 0x8c, 0x21, 0x06,
    /* U+007C '|' */
    0x21, 0x08, 0x42, 0x10, 0x84,
    /* U+007D '}' */
    0xc1, 0x08, 0x63, 0x10, 0x98,
    /* U+007E '~' */
    0x00, 0x00, 0x9b, 0x00, 0x00,
    /* U+2500 '─' */
    0x00, 0x01, 0xf0, 0x00, 0x00,
    /* U+2502 '│' */
    0x21, 0x08, 0x42, 0x10, 0x84,
    /* U+250C '┌' */
    0x00, 0x00, 0x72, 0x10, 0x84,
    /* U+2510 '┐' */
    0x00, 0x01, 0xc2, 0x10, 0x84,
    /* U+2514 '└' */
    0x21, 0x08, 0x70, 0x00, 0x00,
    /* U+2518 '┘' */
    0x21, 0x09, 0xc0, 0x00, 0x00,
    /* U+251C '├' */
    0x21, 0x08, 0x72, 0x10, 0x84,
    /* U+2524 '┤' */
    0x21, 0x09, 0xc2, 0x10, 0x84,
    /* U+252C '┬' */
    0x00, 0x01, 0xf2, 0x10, 0x84,
    /* U+2534 '┴' */
    0x21, 0x09, 0xf0, 0x00, 0x00,
    /* U+253C '┼' */
    0x21, 0x09, 0xf2, 0x10, 0x84,
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
    {.bitmap_index = 0, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 5, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 10, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 15, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 20, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 25, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 30, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 35, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 40, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 45, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 50, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 55, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 60, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 65, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 70, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 75, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 80, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 85, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 90, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 95, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 100, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 105, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 110, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 115, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 120, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 125, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 130, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 135, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 140, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 145, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 150, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 155, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 160, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 165, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 170, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 175, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 180, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 185, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 190, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 195, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 200, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 205, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 210, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 215, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 220, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 225, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 230, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 235, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 240, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 245, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 250, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 255, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 260, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 265, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 270, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 275, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 280, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 285, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 290, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 295, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 300, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 305, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 310, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 315, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 320, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 325, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 330, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 335, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 340, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 345, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 350, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 355, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 360, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 365, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 370, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 375, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 380, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 385, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 390, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 395, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 400, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 405, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 410, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 415, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 420, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 425, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 430, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 435, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 440, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 445, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 450, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 455, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 460, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 465, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 470, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 475, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 480, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 485, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 490, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 495, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 500, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 505, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 510, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 515, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 520, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
    {.bitmap_index = 525, .adv_w = 80, .box_w = 5, .box_h = 8, .ofs_x = 0, .ofs_y = -1},
};

static const uint16_t box_unicode_list[] = {
    0x0000, 0x0002, 0x000c, 0x0010, 0x0014, 0x0018, 0x001c, 0x0024, 0x002c, 0x0034, 0x003c
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 32, .range_length = 95, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    },
    {
        .range_start = 9472, .range_length = 61, .glyph_id_start = 96,
        .unicode_list = box_unicode_list, .glyph_id_ofs_list = NULL, .list_length = 11, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }
};

#if LVGL_VERSION_MAJOR >= 8
static const lv_font_fmt_txt_dsc_t font_dsc = {
#else
static lv_font_fmt_txt_dsc_t font_dsc = {
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 2,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
};

#if LVGL_VERSION_MAJOR >= 8
const lv_font_t lv_font_spleen_5x8 = {
#else
lv_font_t lv_font_spleen_5x8 = {
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 8,
    .base_line = 1,
#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = LV_FONT_SUBPX_NONE,
#endif
#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8
    .underline_position = 0,
    .underline_thickness = 0,
#endif
    .dsc = &font_dsc
};

#endif /* LV_FONT_SPLEEN_5X8 */
