#!/usr/bin/env python3
"""Generate the LVGL v9 2-bpp C font `lv_font_micro_2x3` (fixed 2x3 cell).

The page-thumbnail "font": every glyph of the Tom Thumb 4x6 merged set
(see gen-tomthumb-font.py — Tom Thumb text + misc-fixed 4x6 graphics +
synthesized quadrants) box-filtered down 2x to a 2(w) x 3(h) cell at
2 bpp. 4x6 -> 2x3 is an exact 2x2 box filter: each output pixel is the
mean of a 2x2 block, quantized to the four grey levels.

Deliberately unreadable — it exists to render a WHOLE micron page as a
layout thumbnail (160 columns on a 320 px panel; the "graphics" many
nodes draw at 100+ columns finally fit). Block elements survive the
downsample exactly (a quadrant becomes one full pixel), box lines become
grey traces, text becomes grey texture — you see what's where, then step
the font back up to read.

Coverage is identical to lv_font_tomthumb_4x6 by construction, so
stepping between the two never changes which characters render.

Usage:  scripts/gen-micro-font.py [tom-thumb.bdf] [fixed-4x6.bdf] [out.c]
Defaults: scripts/{tom-thumb,fixed-4x6}.bdf -> src/lcd_ui/lv_font_micro_2x3.c

This is a release-time regeneration step, NOT part of the build — the
generated .c is checked in (like every LVGL font). Re-run alongside
gen-tomthumb-font.py when bumping either source font.
"""
import importlib.util
import sys, os

HERE = os.path.dirname(os.path.abspath(__file__))

# The 4x6 generator owns the BDF parsing + merge; reuse it (dash in the
# filename forces the importlib route).
_spec = importlib.util.spec_from_file_location(
    "gen_tomthumb_font", os.path.join(HERE, "gen-tomthumb-font.py"))
_tt = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_tt)

SRC_W, SRC_H = _tt.CELL_W, _tt.CELL_H       # 4 x 6
CELL_W, CELL_H = SRC_W // 2, SRC_H // 2     # 2 x 3
BPP = 2
MAXV = (1 << BPP) - 1


def downsample(cell4):
    """2x2 box filter: mean of each block, rounded to a 0..MAXV level."""
    out = [[0] * CELL_W for _ in range(CELL_H)]
    for r in range(CELL_H):
        for c in range(CELL_W):
            s = (cell4[2 * r][2 * c] + cell4[2 * r][2 * c + 1] +
                 cell4[2 * r + 1][2 * c] + cell4[2 * r + 1][2 * c + 1])
            out[r][c] = int(s * MAXV / 4.0 + 0.5)
    return out


def pack_cell(cell):
    """Pack a CELL_H x CELL_W cell of 0..MAXV into continuous MSB-first
    BPP-bits-per-pixel bytes."""
    bits = []
    for r in range(CELL_H):
        for c in range(CELL_W):
            for k in range(BPP - 1, -1, -1):
                bits.append((cell[r][c] >> k) & 1)
    out = bytearray()
    for k in range(0, len(bits), 8):
        b = 0
        for j in range(8):
            if k + j < len(bits) and bits[k + j]:
                b |= 1 << (7 - j)
        out.append(b)
    return bytes(out)


def main():
    tom = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "tom-thumb.bdf")
    fix = sys.argv[2] if len(sys.argv) > 2 else os.path.join(HERE, "fixed-4x6.bdf")
    out = sys.argv[3] if len(sys.argv) > 3 else os.path.join(
        HERE, "..", "src", "lcd_ui", "lv_font_micro_2x3.c")

    glyphs = _tt.parse_bdf(fix)
    for cp, cell in _tt.parse_bdf(tom).items():
        glyphs[cp] = cell
    for cp, cell in _tt.quadrant_glyphs().items():
        glyphs.setdefault(cp, cell)

    cps = sorted(glyphs)
    segments = _tt.build_segments(cps)

    entries = []   # (codepoint, packed-bytes, bitmap_index)
    idx = 0
    for cp in cps:
        data = pack_cell(downsample(glyphs[cp]))
        entries.append((cp, data, idx)); idx += len(data)

    L = []
    L.append("/" + "*" * 78)
    L.append(" * Tom Thumb 4x6 merged set box-filtered 2x -> LVGL v9 2-bpp font, 2x3 cell.")
    L.append(" * %d glyphs. The page-THUMBNAIL font: deliberately unreadable, it renders" % len(cps))
    L.append(" * a whole micron page (160 columns at 320 px) so the layout/'graphics' are")
    L.append(" * visible at a glance. Block elements survive exactly (a quadrant becomes")
    L.append(" * one full pixel); box lines and text become grey traces/texture.")
    L.append(" * Generated by scripts/gen-micro-font.py; do not edit.")
    L.append(" *")
    L.append(" * Sources as for lv_font_tomthumb_4x6: Tom Thumb (MIT), misc-fixed 4x6")
    L.append(" * (public domain). See gen-tomthumb-font.py.")
    L.append(" " + "*" * 78 + "/")
    L.append("")
    L.append("#ifdef LV_LVGL_H_INCLUDE_SIMPLE")
    L.append('    #include "lvgl.h"')
    L.append("#else")
    L.append('    #include "lvgl.h"')
    L.append("#endif")
    L.append("")
    L.append("#ifndef LV_FONT_MICRO_2X3")
    L.append("    #define LV_FONT_MICRO_2X3 1")
    L.append("#endif")
    L.append("")
    L.append("#if LV_FONT_MICRO_2X3")
    L.append("")
    L.append("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {")
    for cp, data, _ in entries:
        ch = chr(cp) if 0x20 <= cp <= 0x7E and cp != 0x5C else ""
        L.append("    /* U+%04X%s */ %s," % (cp, " '%s'" % ch if ch else "",
                                             ", ".join("0x%02x" % b for b in data)))
    L.append("};")
    L.append("")
    L.append("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
    L.append("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,")
    for cp, _, bi in entries:
        L.append("    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = 0, .ofs_y = 0},"
                 % (bi, CELL_W * 16, CELL_W, CELL_H))
    L.append("};")
    L.append("")
    sparse_i = 0
    for kind, seg in segments:
        if kind != "sparse":
            continue
        L.append("static const uint16_t unicode_list_%d[] = {" % sparse_i)
        for k in range(0, len(seg), 12):
            L.append("    " + ", ".join("0x%04x" % (cp - seg[0]) for cp in seg[k:k+12]) + ",")
        L.append("};")
        L.append("")
        sparse_i += 1
    L.append("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
    gid = 1
    sparse_i = 0
    for si, (kind, seg) in enumerate(segments):
        comma = "," if si + 1 < len(segments) else ""
        if kind == "range":
            L.append("    {")
            L.append("        .range_start = %d, .range_length = %d, .glyph_id_start = %d,"
                     % (seg[0], len(seg), gid))
            L.append("        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY")
            L.append("    }%s" % comma)
        else:
            span = (seg[-1] - seg[0]) + 1
            L.append("    {")
            L.append("        .range_start = %d, .range_length = %d, .glyph_id_start = %d,"
                     % (seg[0], span, gid))
            L.append("        .unicode_list = unicode_list_%d, .glyph_id_ofs_list = NULL, .list_length = %d, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY"
                     % (sparse_i, len(seg)))
            L.append("    }%s" % comma)
            sparse_i += 1
        gid += len(seg)
    L.append("};")
    L.append("")
    L.append("#if LVGL_VERSION_MAJOR >= 8")
    L.append("static const lv_font_fmt_txt_dsc_t font_dsc = {")
    L.append("#else")
    L.append("static lv_font_fmt_txt_dsc_t font_dsc = {")
    L.append("#endif")
    L.append("    .glyph_bitmap = glyph_bitmap,")
    L.append("    .glyph_dsc = glyph_dsc,")
    L.append("    .cmaps = cmaps,")
    L.append("    .kern_dsc = NULL,")
    L.append("    .kern_scale = 0,")
    L.append("    .cmap_num = %d," % len(segments))
    L.append("    .bpp = %d," % BPP)
    L.append("    .kern_classes = 0,")
    L.append("    .bitmap_format = 0,")
    L.append("};")
    L.append("")
    L.append("#if LVGL_VERSION_MAJOR >= 8")
    L.append("const lv_font_t lv_font_micro_2x3 = {")
    L.append("#else")
    L.append("lv_font_t lv_font_micro_2x3 = {")
    L.append("#endif")
    L.append("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,")
    L.append("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    L.append("    .line_height = %d," % CELL_H)
    L.append("    .base_line = 0,")
    L.append("#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)")
    L.append("    .subpx = LV_FONT_SUBPX_NONE,")
    L.append("#endif")
    L.append("#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8")
    L.append("    .underline_position = 0,")
    L.append("    .underline_thickness = 0,")
    L.append("#endif")
    L.append("    .dsc = &font_dsc")
    L.append("};")
    L.append("")
    L.append("#endif /* LV_FONT_MICRO_2X3 */")
    L.append("")

    out = os.path.normpath(out)
    with open(out, "w") as f:
        f.write("\n".join(L))
    n_range = sum(1 for k, _ in segments if k == "range")
    print("wrote %s (%d glyphs, %d bitmap bytes, %d bpp, %d cmaps: %d range + %d sparse)"
          % (out, len(cps), idx, BPP, len(segments), n_range, len(segments) - n_range))


if __name__ == "__main__":
    main()
