#!/usr/bin/env python3
"""Generate an LVGL v9 1-bpp C font from the Spleen 5x8 BDF.

Spleen (https://github.com/fcambus/spleen) is a monospaced bitmap font,
BSD-2-Clause. This emits the printable-ASCII range (0x20..0x7E) as a fixed
5x8 cell font matching LVGL's `lv_font_fmt_txt` layout — the same structure
LVGL's own `lv_font_unscii_8.c` uses, so it compiles unchanged here.

Each glyph is stored as a full 5(w) x 8(h) cell (true monospace), 1 bpp,
bits packed continuously row-major MSB-first. Metrics: adv_w = 5 px,
line_height = 8, base_line = 1 (Spleen's FONT_DESCENT).

Usage:  scripts/gen-spleen-font.py [spleen-5x8.bdf] [out.c]
Defaults: scripts/spleen-5x8.bdf -> src/lcd_ui/lv_font_spleen_5x8.c

This is a release-time regeneration step, NOT part of the build — the
generated .c is checked in (like every LVGL font). Re-run only when bumping
the Spleen version.
"""
import sys, os

FIRST, LAST = 0x20, 0x7E          # printable ASCII
CELL_W, CELL_H = 5, 8


def parse_bdf(path):
    """Return {codepoint: list-of-8 row-strings of '0'/'1' width CELL_W}."""
    with open(path, "r") as f:
        lines = f.read().splitlines()

    # Font bounding box: width height xoff yoff
    fbb = None
    for ln in lines:
        if ln.startswith("FONTBOUNDINGBOX"):
            _, w, h, x, y = ln.split()
            fbb = (int(w), int(h), int(x), int(y))
            break
    if fbb is None:
        raise SystemExit("no FONTBOUNDINGBOX")
    _, _, fbbx, fbby = fbb

    glyphs = {}
    i = 0
    n = len(lines)
    while i < n:
        if lines[i].startswith("STARTCHAR"):
            enc, bbx, bitmap = None, None, []
            i += 1
            while i < n and not lines[i].startswith("ENDCHAR"):
                ln = lines[i]
                if ln.startswith("ENCODING"):
                    enc = int(ln.split()[1])
                elif ln.startswith("BBX"):
                    _, bw, bh, bx, by = ln.split()
                    bbx = (int(bw), int(bh), int(bx), int(by))
                elif ln.startswith("BITMAP"):
                    i += 1
                    while i < n and not lines[i].startswith("ENDCHAR"):
                        bitmap.append(lines[i].strip())
                        i += 1
                    break
                i += 1
            # advance past ENDCHAR
            while i < n and not lines[i].startswith("ENDCHAR"):
                i += 1
            i += 1
            if enc is None or bbx is None or not (FIRST <= enc <= LAST):
                continue

            bw, bh, bx, by = bbx
            # Blit the glyph's bbox into a blank CELL_H x CELL_W cell.
            cell = [[0] * CELL_W for _ in range(CELL_H)]
            top_row = (fbby + CELL_H) - (by + bh)   # row of glyph's top pixel
            left_col = bx - fbbx
            for j in range(bh):
                if j >= len(bitmap):
                    break
                rowbytes = bytes.fromhex(bitmap[j]) if bitmap[j] else b""
                for c in range(bw):
                    byte_i = c // 8
                    if byte_i >= len(rowbytes):
                        continue
                    bit = (rowbytes[byte_i] >> (7 - (c % 8))) & 1
                    if not bit:
                        continue
                    rr, cc = top_row + j, left_col + c
                    if 0 <= rr < CELL_H and 0 <= cc < CELL_W:
                        cell[rr][cc] = 1
            glyphs[enc] = cell
        else:
            i += 1
    return glyphs


def pack_cell(cell):
    """Pack a CELL_H x CELL_W cell into continuous MSB-first 1-bpp bytes."""
    bits = []
    for r in range(CELL_H):
        for c in range(CELL_W):
            bits.append(cell[r][c])
    out = bytearray()
    for k in range(0, len(bits), 8):
        b = 0
        for j in range(8):
            if k + j < len(bits) and bits[k + j]:
                b |= 1 << (7 - j)
        out.append(b)
    return bytes(out)


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    bdf = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "spleen-5x8.bdf")
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        here, "..", "src", "lcd_ui", "lv_font_spleen_5x8.c")

    glyphs = parse_bdf(bdf)
    codes = list(range(FIRST, LAST + 1))
    glyph_bytes = pack_cell([[0] * CELL_W for _ in range(CELL_H)])  # blank fallback
    bytes_per = len(glyph_bytes)

    bitmaps, dscs = [], []
    idx = 0
    for cp in codes:
        cell = glyphs.get(cp)
        data = pack_cell(cell) if cell else glyph_bytes
        bitmaps.append((cp, data, idx))
        dscs.append((idx, cp))
        idx += len(data)

    L = []
    L.append("/" + "*" * 78)
    L.append(" * Spleen 5x8 -> LVGL v9 1-bpp font (printable ASCII 0x20-0x7E).")
    L.append(" * Generated by scripts/gen-spleen-font.py from Spleen's BDF; do not edit.")
    L.append(" *")
    L.append(" * Spleen (c) 2018-2026 Frederic Cambus, BSD-2-Clause.")
    L.append(" * https://github.com/fcambus/spleen")
    L.append(" " + "*" * 78 + "/")
    L.append("")
    L.append("#ifdef LV_LVGL_H_INCLUDE_SIMPLE")
    L.append('    #include "lvgl.h"')
    L.append("#else")
    L.append('    #include "lvgl.h"')
    L.append("#endif")
    L.append("")
    L.append("#ifndef LV_FONT_SPLEEN_5X8")
    L.append("    #define LV_FONT_SPLEEN_5X8 1")
    L.append("#endif")
    L.append("")
    L.append("#if LV_FONT_SPLEEN_5X8")
    L.append("")
    L.append("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {")
    for cp, data, _ in bitmaps:
        ch = chr(cp) if cp not in (0x5C,) else "\\\\"
        L.append("    /* U+%04X '%s' */" % (cp, ch))
        L.append("    " + ", ".join("0x%02x" % b for b in data) + ",")
    L.append("};")
    L.append("")
    L.append("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
    L.append("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,")
    for bi, cp in dscs:
        L.append("    {.bitmap_index = %d, .adv_w = %d, .box_w = %d, .box_h = %d, .ofs_x = 0, .ofs_y = -1},"
                 % (bi, CELL_W * 16, CELL_W, CELL_H))
    L.append("};")
    L.append("")
    L.append("static const lv_font_fmt_txt_cmap_t cmaps[] = {")
    L.append("    {")
    L.append("        .range_start = %d, .range_length = %d, .glyph_id_start = 1," % (FIRST, len(codes)))
    L.append("        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY")
    L.append("    }")
    L.append("};")
    L.append("")
    L.append("#if LVGL_VERSION_MAJOR >= 8")
    L.append("static const lv_font_fmt_txt_dsc_t font_dsc = {")
    L.append("#else")
    L.append("static lv_font_fmt_txt_dsc_t font_dsc = {")
    L.append("#endif")
    L.append("    .glyph_bitmap = glyph_bitmap,")
    L.append("    .glyph_dsc = glyph_dsc,")
    L.append("    .cmaps = cmaps,")
    L.append("    .kern_dsc = NULL,")
    L.append("    .kern_scale = 0,")
    L.append("    .cmap_num = 1,")
    L.append("    .bpp = 1,")
    L.append("    .kern_classes = 0,")
    L.append("    .bitmap_format = 0,")
    L.append("};")
    L.append("")
    L.append("#if LVGL_VERSION_MAJOR >= 8")
    L.append("const lv_font_t lv_font_spleen_5x8 = {")
    L.append("#else")
    L.append("lv_font_t lv_font_spleen_5x8 = {")
    L.append("#endif")
    L.append("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,")
    L.append("    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,")
    L.append("    .line_height = %d," % CELL_H)
    L.append("    .base_line = 1,")
    L.append("#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)")
    L.append("    .subpx = LV_FONT_SUBPX_NONE,")
    L.append("#endif")
    L.append("#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8")
    L.append("    .underline_position = 0,")
    L.append("    .underline_thickness = 0,")
    L.append("#endif")
    L.append("    .dsc = &font_dsc")
    L.append("};")
    L.append("")
    L.append("#endif /* LV_FONT_SPLEEN_5X8 */")
    L.append("")

    out = os.path.normpath(out)
    with open(out, "w") as f:
        f.write("\n".join(L))
    print("wrote %s (%d glyphs, %d bitmap bytes)" % (out, len(codes), idx))


if __name__ == "__main__":
    main()
